"""
SQL DDL (and optional DML) exporter.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterator

import pandas as pd

from ..config import ColumnConfig, Dialect, GeneratorConfig, RelationConfig, TableConfig
from ..schema_builder import SchemaGraph


_TYPE_MAP: dict[Dialect, dict[str, str]] = {
    Dialect.POSTGRES: {
        "int": "INTEGER",
        "bigint": "BIGINT",
        "float": "DOUBLE PRECISION",
        "decimal": "NUMERIC(18,4)",
        "varchar": "VARCHAR",
        "text": "TEXT",
        "date": "DATE",
        "timestamp": "TIMESTAMP",
        "boolean": "BOOLEAN",
        "uuid": "UUID",
    },
    Dialect.SQLITE: {
        "int": "INTEGER",
        "bigint": "INTEGER",
        "float": "REAL",
        "decimal": "REAL",
        "varchar": "TEXT",
        "text": "TEXT",
        "date": "TEXT",
        "timestamp": "TEXT",
        "boolean": "INTEGER",
        "uuid": "TEXT",
    },
    Dialect.MYSQL: {
        "int": "INT",
        "bigint": "BIGINT",
        "float": "DOUBLE",
        "decimal": "DECIMAL(18,4)",
        "varchar": "VARCHAR",
        "text": "TEXT",
        "date": "DATE",
        "timestamp": "DATETIME",
        "boolean": "TINYINT(1)",
        "uuid": "VARCHAR",
    },
    Dialect.SQLSERVER: {
        "int": "INT",
        "bigint": "BIGINT",
        "float": "FLOAT",
        "decimal": "DECIMAL(18,4)",
        "varchar": "NVARCHAR",
        "text": "NVARCHAR(MAX)",
        "date": "DATE",
        "timestamp": "DATETIME2",
        "boolean": "BIT",
        "uuid": "UNIQUEIDENTIFIER",
    },
}

_QUOTE: dict[Dialect, tuple[str, str]] = {
    Dialect.POSTGRES: ('"', '"'),
    Dialect.SQLITE: ('"', '"'),
    Dialect.MYSQL: ('`', '`'),
    Dialect.SQLSERVER: ('[', ']'),
}


class SqlExporter:
    def __init__(self, config: GeneratorConfig) -> None:
        self.config = config
        self.dialect = config.dialect
        self.output_dir = config.output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self._type_map = _TYPE_MAP[self.dialect]
        self._q_open, self._q_close = _QUOTE[self.dialect]

    def generate_ddl(self, graph: SchemaGraph) -> str:
        lines = [f"-- Generated by synthetic-data | dialect: {self.dialect.value}", ""]
        for table in reversed(graph.topological_order()):
            lines.append(self._drop_table(table.name))
        lines.append("")
        for table in graph.topological_order():
            lines.append(self._create_table(table))
        for relation in graph.relations:
            lines.append(self._add_fk(relation))
        return "\n".join(lines) + "\n"

    def export(
        self,
        graph: SchemaGraph,
        tables_and_chunks: list[tuple[TableConfig, Iterator[pd.DataFrame]]] | None = None,
    ) -> Path:
        out_path = self.output_dir / "schema.sql"
        with open(out_path, "w", encoding="utf-8") as handle:
            handle.write(self.generate_ddl(graph))
            if self.config.export_dml and tables_and_chunks:
                handle.write("\n-- DML: INSERT statements\n")
                for table, chunks in tables_and_chunks:
                    for chunk in chunks:
                        handle.write(self._inserts(table, chunk))
        return out_path

    def _q(self, value: str) -> str:
        return f"{self._q_open}{value}{self._q_close}"

    def _drop_table(self, table_name: str) -> str:
        if self.dialect is Dialect.POSTGRES:
            return f"DROP TABLE IF EXISTS {self._q(table_name)} CASCADE;"
        return f"DROP TABLE IF EXISTS {self._q(table_name)};"

    def _sql_type(self, column: ColumnConfig) -> str:
        base = self._type_map[column.dtype.value]
        if column.dtype.value == "varchar":
            if self.dialect is Dialect.SQLITE:
                return base
            max_length = column.max_length or 255
            return f"{base}({max_length})"
        return base

    def _create_table(self, table: TableConfig) -> str:
        column_defs: list[str] = []
        for column in table.columns:
            nullable = "" if column.nullable else " NOT NULL"
            unique = " UNIQUE" if column.unique and column.name != table.pk_column else ""
            column_defs.append(
                f"    {self._q(column.name)} {self._sql_type(column)}{nullable}{unique}"
            )
        column_defs.append(f"    PRIMARY KEY ({self._q(table.pk_column)})")
        return f"CREATE TABLE {self._q(table.name)} (\n" + ",\n".join(column_defs) + "\n);\n"

    def _add_fk(self, relation: RelationConfig) -> str:
        constraint_name = f"fk_{relation.source_table}_{relation.source_column}"
        return (
            f"ALTER TABLE {self._q(relation.source_table)}\n"
            f"    ADD CONSTRAINT {constraint_name}\n"
            f"    FOREIGN KEY ({self._q(relation.source_column)})\n"
            f"    REFERENCES {self._q(relation.target_table)} ({self._q(relation.target_column)});\n"
        )

    def _inserts(self, table: TableConfig, df: pd.DataFrame, batch: int = 500) -> str:
        columns = ", ".join(self._q(col) for col in df.columns)
        rows = df.values.tolist()
        statements: list[str] = []
        for start in range(0, len(rows), batch):
            batch_rows = rows[start:start + batch]
            values_sql = ",\n    ".join(
                "(" + ", ".join(_sql_val(value) for value in row) + ")" for row in batch_rows
            )
            statements.append(
                f"INSERT INTO {self._q(table.name)} ({columns}) VALUES\n    {values_sql};\n"
            )
        return "\n".join(statements)


def _sql_val(value: object) -> str:
    if value is None or (isinstance(value, float) and value != value):
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    safe = str(value).replace("'", "''")
    return f"'{safe}'"
